#!/usr/bin/env python
# -*- utf-8 -*-

from link.engine.core import Engine
from argparse import ArgumentParser


if __name__ == '__main__':
    parser = ArgumentParser()

    parser.add_argument('-n', '--name', help='Engine\'s name')

    args = parser.parse_args()

    enginecls = Engine.new(args.name)
    engine = enginecls()
    engine()
